"""Initial Migration

Revision ID: 978169db352a
Revises: b985295aa318
Create Date: 2020-11-01 17:37:53.322565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978169db352a'
down_revision = 'b985295aa318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('slug', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'slug')
    # ### end Alembic commands ###
